### ISSUE TITLE
Ensure MongoDB backups are sufficient

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#103]
**Describe the feature you'd like and what it will do**

Make sure we have a plan/strategy to back up the MongoDB catalog database.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

Hopefully not needed, but plan for disaster recovery.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

Just need to be clear on whether/how/how often this is happening and/or whether it is needed.

**Additional context**

NA

**Comment by sblack-usu** [comment]
Backup policies we may work with. https://www.mongodb.com/docs/atlas/backup/cloud-backup/scheduling/

**Comment by sblack-usu** [comment]
Here is the current backup policy we are using in Atlas.  An admin may take a snapshot on demand or restore a snapshot through the atlas interface.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/35820390/217071690-554d6c18-ad95-413e-a922-ded8992d36bf.png">

**Comment by sblack-usu** [comment]
TODO: Scott: Change the target times to target the end of the day instead of the beginning of business periods (10:00 UTC) - taking place at 5 AM east west coast time.
