### ISSUE TITLE
Ensure only public/published resources are cataloged for discovery

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#104]
**Describe the feature you'd like and what it will do**

Users submitting datasets through the CZNet Data Submission Portal may or may not make those datasets public/discoverable/published. In the automated functionality that copies metadata from the Data Submission Portal to the catalog database, only metadata for resources that are public, discoverable, or published with a DOI should be transferred to the catalog database.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

We don't want to allow discovery of or disclose metadata for private resources.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

Just need to verify that we are implementing appropriate safeguards to prevent metadata about private resources from ending up in the catalog database.

**Additional context**

NA

**Comment by sblack-usu** [comment]
This needs a bit of design around it before I can implement. I have developed the ability to sync a submission to the search catalog, but I currently do not take into account whether a submission is public/private.

I think the simplest and most generalized solution is to simply loop through all the submissions daily and check the public endpoint for the submissions, then add/remove from the search database as appropriate.  This would also give us the opportunity to ensure the metadata is kept up to date.

The same function that checks for public/private of a submission could also check whether the metadata is up to date and could also be called as needed for triggering updates by the user manually.

I'm going to move forward with the daily job that checks submissions unless @horsburgh or someone else has a strong opinion against this solution.

**Comment by horsburgh** [comment]
@sblack-usu - I think your proposal kills two birds with one stone. A daily job would handle everything that is registered with the DSP nicely. If a resource meets any of the criteria for the public being able to view its metadata (a resources is public, published, discoverable), then it should get added to the catalog.  I realize that I'm using HydroShare's states of public, published, discoverable, but I'm guessing that anything in EarthChem and Zenodo can be mapped to those states.

A daily job should also verify that if the status of something changes from public to private, its metadata should be removed from the catalog. And, I like that a daily fetch would keep things up to date in the catalog with any changes that may have occurred in the repository.

There will still be a bunch of datasets in the catalog (Legacy CZO datasets) that are not registered with the DSP and so would not be regularly updated. We should address those as well. Our assumption is that the Legacy CZO datasets would change much less frequently (if ever), but it is possible.

The downside of a daily job is that a user who submits a dataset through the DSP or registers a dataset with the DSP probably has the expectation that the dataset will immediately appear in the catalog. Would it be possible to also trigger the immediate deposition of metadata to the catalog if you check the repository and find that the registered/submitted dataset is public, published, or discoverable? Alternatively, upon submission we could report to the user that it may take up to 24 hours for their dataset to appear in the catalog. We probably should have some messaging like this anyway to alert users that they need to share or publish their datasets if they want anyone to be able to see them (because we don't have access control functionality in the DSP).
