### ISSUE TITLE
Zenodo submissions can now use the Funding metadata element

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#107]
**Describe the feature you'd like and what it will do**

We have been using the "Additional Notes" metadata field in Zenodo to capture funding agency information because the NSF Awards were not available for selections from Zenodo's index of available awards. It looks like their database of awards has been updated, and the NSF awards for the CZHub and CZNet projects are now included. So, we should be able to use the Funding element and dispense with putting funding information in the "Additional Notes" metadata field. 

**Why is this feature important?**

We want users to specify accurate metadata about the funding agency and award for their work.

**Is your feature request related to a problem? Please describe.**

This was a problem in the past, but should be resolved now that the awards exist in Zenodo's database of funded projects.

**Additional context**

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/3485902/228087435-01d5fb62-0e0b-49c9-b680-c07099331203.png">

**Comment by Maurier** [comment]
This has been implemented.
