### ISSUE TITLE
Zenodo authorization fails

### ISSUE THREAD

**Issue by Maurier** [cznethub/dsp#127]
**Description of the bug**
Authorizing Zonodo often fails with the error `invalid_grant`. It can be reproduced somewhat consistently, but it also succeeds at times, making the authorization process unreliable. 

Steps to reproduce the bug:
1. Go to Account & Settings page.
2. Go to the Authorized Repositories tab.
3. Try to authorize and deauthorize Zenodo multiple times.
4. Authorization will often fail with the error `invalid_grant`.

**Expected behavior**
Authorization and deauthorization work as expected.

**Additional information**
Zenodo OAuth 2.0 endpoints:
![image](https://github.com/cznethub/dsp/assets/2448568/d7e68a37-ad75-4c11-a5b9-6407c50f47b1)
From https://zenodo.org/account/settings/applications/, click on item under Developer applications.

DSP configuration:
https://github.com/cznethub/dspback/blob/develop/dspback/routers/repository_authorization.py#L37
https://github.com/cznethub/dspback/blob/develop/dspback/config/__init__.py#L115

Approach:
- [x] Try to resend the request upon failure.
   - Did not work. Another error is thrown if the request is retried.
- [x] Try updating `authlib` dependencies to a newer version.
   - Did not work.
- [x] Monitor the outgoing request and look for errors in implementation.
   - The requests look correct.
- [x] Try to reproduce the issue in an isolated project without any authentication libraries.
   - An issue has been created at https://github.com/zenodo/zenodo-rdm/issues/878
   - [ ] It would be good to include a reproducible link.
- [x] Fail gracefully. Restart authorization process?

**Comment by pkdash** [comment]
@Maurier I have created this [ticket ](https://github.com/zenodo/zenodo-rdm/issues/878)in Zenodo.

**Comment by Maurier** [comment]
@horsburgh - I need a message to show on the authorization popup upon failure. Do you have a suggestion?

![image](https://github.com/user-attachments/assets/72e38719-0a21-4494-b48d-336c26ee6da5)

**Comment by horsburgh** [comment]
It should say:

"The authorization attempt failed. But, we often have this issue with Zenodo due to an issue with their application programming interface. Please click the "Retry Authorization" button below to try again. It may take several attempts for the authorization to succeed. If you can't successfully authorize after several attempts, please contact us and we will investigate."

**Comment by Maurier** [comment]
At this point we have done everything we can on our end to address this issue. Closing.
