### ISSUE TITLE
Search function improvements

### ISSUE THREAD

**Issue by Maurier** [cznethub/dsp#129]
**Describe the feature you'd like and what it will do**
Improvements to the search function
- Improve relevancy of search results.
- When performing a search with no 'term' provided, return all search results sorted by recent date.

**Why is this feature important?**
This feature is needed to make the search more intuitive.

**Is your feature request related to a problem? Please describe.**
This came up as feedback in recent testing.

> Clearing the search box on the search result page does not clear the search results. Do a search with a term. Then delete the term from the search box and hit enter. I don’t think anything changes. Then, filters still are operating on the previous search result.
Search results not clearing correctly. Click “Browse data products” on the main page or Search For “CZNet”. Then, select Zenodo as the repository. THere is one resource returned. Then, clear the search term and hit enter. The one resource remains. Then hit clear filters. The one resource remains. With no search term and not filters cleared I should be back to all of the resources available.

**Additional context**
These improvements have already been done in iGuide catalog, so we should reuse that implementation.

**Comment by horsburgh** [comment]
@Maurier - does this issue belong in the DSP repository or should this be in the Catalog repository?

**Comment by Maurier** [comment]
> @Maurier - does this issue belong in the DSP repository or should this be in the Catalog repository?

You are right. I have moved it here: https://github.com/cznethub/cznet-discovery/issues/31
