### ISSUE TITLE
Unable to register EarthChem resource

### ISSUE THREAD

**Issue by Maurier** [cznethub/dsp#130]
**Description of the bug**
A user was unable to register an EarthChem resource at https://ecl.earthchem.org/view.php?id=3369. The UI (erroneously) shows an error about not being able to find the resource.

I was able to reproduce the issue they are seeing and it seems to be caused by a schema validation error:

```
Request data validation errors: 1 validation error for EarthChemMetadataResponse
response -> metadata -> contributors
  ensure this value has at most 3 items (type=value_error.list.max_items; limit_value=3)
```

Our EarthChem schema indeed specifies a maximum limit of 3 contributors for a resource, but this resource contains more than a dozen.

Possible solutions:
- Update our schema to support any number of contributors.
- Register the resource and fetch data for at most the first 3 contributors.
- Reject the resource registration and improve error handling (Not idea, in my opinion).

@horsburgh - Let us know which option would work best.

**Comment by horsburgh** [comment]
Not sure why we would have limited the schema to 3 contributors. I suggest the option to allow more, as there is an obvious need for this.
