### ISSUE TITLE
External Record has disabled save button

### ISSUE THREAD

**Issue by sblack-usu** [cznethub/dsp#16]
**Description of the bug**
I filled out all the required fields for an external record and the save button did not enable.  There are no more red-highlighted fields on the form.

Steps to reproduce the bug:
1. Go to create an External Record
2. Fill in all red-marked required fields
3. Observe the save button is disabled

**Expected behavior**
I would expect the save button to enable when all required fields are filled in.  I also think we should be able to save a record without all the required fields.

**Comment by Maurier** [comment]
This looks like an issue with a renderer. The 'Provider' field is also required, but the UI does not indicate so.

![image](https://user-images.githubusercontent.com/2448568/156016104-2297dbb7-7444-44ba-bad5-a38cc3429d8a.png)

![image](https://user-images.githubusercontent.com/2448568/156016182-cd0ca398-a3ef-4d20-a335-4cdbce01307b.png)
