### ISSUE TITLE
Exported CSV elements need tweaks

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#25]
**Description of the bug**

In the CSV file exported from the My Submissions Page, the following need to be corrected:
* Publication date is given as some number that a mere mortal will not be able to interpret as a date. The date needs to be formatted as an ISO 8601 date string - e.g., YYYY-MM-DD HH:MM:SS
* The name of the repository should be capitalized

Steps to reproduce the bug:
1. Navigate to the My Submissions Page
2. Click on the "Export Submissions" button
3. View the resulting CSV
4. See issues

**Expected behavior**

Date will be formatted as an ISO 8601 string. Repository name will be capitalized.

**Additional information**

[CZNet_submissions.csv](https://github.com/cznethub/dsp/files/8273508/CZNet_submissions.csv)

**Comment by Maurier** [comment]
Here is a sample file after implementing these changes.

[CZNet_submissions.csv](https://github.com/cznethub/dsp/files/8759842/CZNet_submissions.csv)
