### ISSUE TITLE
Consider delete submission from DSP without delete from repository

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#26]
**Describe the feature you'd like and what it will do**

Consider an option to allow users to delete the submission from the DSP without deleting the corresponding resource from the repository in which it resides.

**Why is this feature important?**

A user may want to remove a submission from their list of My Submissions without deleting that resource from the repository where it resides.

**Is your feature request related to a problem? Please describe.**

No

**Additional context**

N/A

**Comment by sblack-usu** [comment]
The endpoint exists, we just need a button wired up in the frontend
DELETE `/api/submit/{repo}/{id}`

**Comment by Maurier** [comment]
We could accommodate a checkbox on the confirmation window so it reads 'Also delete in repository'. Probably unchecked by default just to be safe, but we can have the app remember the state.

**Comment by Maurier** [comment]
@sblack-usu This is pending modification to the original delete method (`/api/metadata/${repository}/${identifier}`). We need to prevent it from attempting to delete the submission in the repository.

Deleting submissions in the repository will be done specifically via DELETE `/api/submit/{repo}/{id}`

**Comment by Maurier** [comment]
Closed pending api changes.
