### ISSUE TITLE
Verify that example input is provided for fields with a required format

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#28]
**Describe the feature you'd like and what it will do**

Go through the metadata submission forms and make sure an example is provided where we are expecting input in a particular format. For example - when a user is inputting an ORCID, are they just inputting the identifier or are they inputting the URL-encoded ORCID? This applies to other fields as well - e.g., names. Should it be "Jeffery S. Horsburgh" or "Horsburgh, Jeffery S."

These should also be enforced on the JSON schema.

**Why is this feature important?**

Save users time and frustration in figuring out what to input.

**Is your feature request related to a problem? Please describe.**

N/A

**Additional context**

![image](https://user-images.githubusercontent.com/3485902/158687781-0fb2e63b-b0f6-442b-b72f-813b360318ce.png)

**Comment by Maurier** [comment]
Also, we should make all field descriptions human-readable as part of this work.

**Comment by Maurier** [comment]
Example input has been added to various fields, and help texts have been made more human-readable. We might still want to improve on the latter, but we'll add another issue if that is the case.
