### ISSUE TITLE
Remove RelationType grouping on Register Dataset page

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#30]
**Description of the bug**

Remove the extra "Relation type" grouping in the "Related Resources section of the Register Dataset page. This is redundant and not needed.

Steps to reproduce the bug:
1. Go to the Register Dataset page
2. Click on the + button to add a related resoure
3. See extra grouping around "Relation type"

**Expected behavior**

The Relation Type drop down menu will appear without the "Relation type" grouping around it.

**Additional information**

![image](https://user-images.githubusercontent.com/3485902/158689617-f2007fa1-54c2-4be6-8a35-d2d1b985a5ba.png)

**Comment by Maurier** [comment]
This has already been fixed.
