### ISSUE TITLE
Add ability for user to supply HydroShare profile link for a creator

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#31]
**Describe the feature you'd like and what it will do**

On the submit to HydroShare page, enable the metadata element that allows users to specify the HydroShare profile for the creator to link that creator to their HydroShare profile. This metadata field is optional. The link should be provided as a URL to the profile. For example:

https://www.hydroshare.org/user/10/

**Why is this feature important?**

Completes metadata for a creator in HydroShare.

**Is your feature request related to a problem? Please describe.**

N/A

**Additional context**

N/A

**Comment by Maurier** [comment]
@horsburgh Should this optional field also be added to Contributors?

**Comment by horsburgh** [comment]
@Maurier - this functionality should create the same information that is created in HydroShare when one adds a contributor. In HydroShare, you have the option to create a contributor from a HydroShare user or by filling in a form about another person. So, whatever metadata is created by HydroShare when you add a contributor to the resource, the DSP should create the same metadata. Since you don't have the option of searching the list of HydroShare users to add a contributor to a resource in DSP, you should just provide the full set of metadata fields for the DSP user to fill out (including the optional HydroShare profile link).

Is that consistent with your thinking?

**Comment by Maurier** [comment]
Yes, that makes sense.
