### ISSUE TITLE
Consider vertical spacing of metadata elements

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#33]
**Describe the feature you'd like and what it will do**

Metadata elements like Creators, Contributors, and Funding agency information are repeatable and currently take up a lot of vertical space on the form. This requires users to do a lot of vertical scrolling. Consider reducing the amount of vertical space required by these elements to reduce required scrolling.

**Why is this feature important?**

Users could miss important/required information and elements on the page because there's a lot of scrolling going on. Users may also find this annoying.

**Is your feature request related to a problem? Please describe.**

N/A

**Additional context**

N/A

**Comment by Maurier** [comment]
Significant improvements have been made to reduce vertical space.
- Organize elements in multiple columns
- Make array elements collapsible
