### ISSUE TITLE
Change labels on spatial coverage coordinates to add valid values

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#34]
**Describe the feature you'd like and what it will do**

Change the labels on the coverage coordinates as follows:

For Point Coverage East Coordinate: The coordinate of the point location measured in the east direction (between -180 and 180)
For Point Coverage North Coordinate: The coordinate of the point location measured in the north direction (between -90 and 90)

For Box Coverage North limit: The coordinate of the point location measured in the north direction (between -90 and 90)
For Box Coverage East limit: The coordinate of the point location measured in the east direction (between -180 and 180)
For Box Coverage South limit: The coordinate of the point location measured in the north direction (between -90 and 90)
For Box Coverage West Limit: The coordinate of the point location measured in the east direction (between -180 and 180)

**Why is this feature important?**

Specifies valid values that can be supplied by users.

**Is your feature request related to a problem? Please describe.**

N/A

**Additional context**

N/A

**Comment by Maurier** [comment]
This has been implemented already.
