### ISSUE TITLE
Make file selection and moving to folders more intuitive for HydroShare

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#36]
**Describe the feature you'd like and what it will do**

It took me about 5 minutes to figure out how to get a file into a folder and I’m still not sure I can consistently get it to work. Is there any chance drag and drop can be added? Could we possibly do the following:

* Get rid of the check boxes and use highlighting for selection
* Multiple selection will be done via keyboard controls just like the operating system

**Why is this feature important?**

Users may struggle to move files into and out of folders using the current functionality.

**Is your feature request related to a problem? Please describe.**

N/A

**Additional context**

![image](https://user-images.githubusercontent.com/3485902/158692504-0b0f949a-84b3-4816-a77b-2230c1259806.png)

**Comment by Maurier** [comment]
@horsburgh -  While the drag and drop might be a little too  complicated to implement right now, the keyboard shortcuts and removing the checkboxes  should be straightforward enough to include in our first release.

So, I think we should add this issue to the milestone and aim for this initial behavior to be added, and add the drag and drop functionality at a later point.

**Comment by horsburgh** [comment]
@Maurier - added it to the milestone.

**Comment by Maurier** [comment]
Implemented as described. Pending drag and drop functionality to be added in the future.
