### ISSUE TITLE
Sort out funding agency information for Zenodo submission

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#38]
**Description of the bug**

We had to make the "Grants" element for Zenodo optional because their schema requires that we submit a DOI for a grant. We have no way for users to sort out what the DOIs are for grants so they can be entered, and many NSF grants to not appear in Zenodo's database anyway. We want to make sure funding agency information is entered into Zenodo resources. Their user interface suggests using the "Additional Notes" field for grants not in the OpenAire database. Funding agency information we need to capture include:

* Funding Agency
* Award Title
* Award Number
* Award URL

Steps to reproduce the bug:
1. Go to the Submit to Zenodo page
2. Click on the + to add a new grant
3. The user has no way to know what to enter where it asks for "Grant Identifier with DOI prefix"

**Expected behavior**

We may have to abandon using the "Grants" element in favor of capturing the funding agency information above and putting it in the "Additional Notes" field.

**Additional information**

![image](https://user-images.githubusercontent.com/3485902/158693576-71a41072-521c-465a-87e8-8b0d3f133a59.png)

**Comment by sblack-usu** [comment]
https://github.com/cznethub/dspback/pull/57
