### ISSUE TITLE
Split Submission Vue component to its own repository

### ISSUE THREAD

**Issue by sblack-usu** [cznethub/dsp#46]
**Describe the feature you'd like and what it will do**
To encourage reuse of this vue component across our projects, split the vue component into its own repository and pull it in as a dependency in dspfront

**Why is this feature important?**
Encourages reuse and perhaps some community support.

**Is your feature request related to a problem? Please describe.**
Not a problem, just would like to make this component reusable.

**Comment by horsburgh** [comment]
As part of our reorganization of GitHub repositories, this should get done with the next milestone.

**Comment by Maurier** [comment]
This has been done, pending swap in dspfront repository once changes as part of iGuide settle.
