### ISSUE TITLE
Configurable branding of dspfront

### ISSUE THREAD

**Issue by sblack-usu** [cznethub/dsp#47]
**Describe the feature you'd like and what it will do**
Update all site branding to be configurable and document how to do it.  This will be useful when other groups come along that would like to collect and submit standardized submissions across repositories.

**Why is this feature important?**
This allows us to manage multiple Data Submission Portals for different groups.

**Comment by Maurier** [comment]
This has been implemented by leveraging internationalization techniques and Vuetify theming capabilities. Documented in README file.
