### ISSUE TITLE
Repository authorization status and management

### ISSUE THREAD

**Issue by sblack-usu** [cznethub/dsp#49]
**Describe the feature you'd like and what it will do**
I'd like to authorize and deauthorize each repository from a single page.

**Why is this feature important?**
Currently there is no way to deauthorize a repository in the UI or clearly see which repositories and users are attached to my account.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't know which accounts are attached to my user.

**Comment by horsburgh** [comment]
Maybe the best place to do this would be via a simple user profile page?

**Comment by horsburgh** [comment]
The profile page exists now. We should add the ability to deauthorize on the same page. Once authorized, there could just be a "de-authorize" button on the same page. 

![image](https://user-images.githubusercontent.com/3485902/215650348-8bc33a24-3992-49a3-aab5-fd84c633de01.png)

**Comment by Maurier** [comment]
This ability has been added and will be included in our next release.
