### ISSUE TITLE
Funding Identifiers are not returned from EarthChem

### ISSUE THREAD

**Issue by sblack-usu** [cznethub/dsp#58]
**Description of the bug**
Create a new EarthChem record with the properties filled out for funder -> identifiers -> (Scheme, Scheme URI, Identifier, Url).  The EarthChem record is created but when it is retrieved, identifiers is None.  The json-schema validation fails and an error results.

Steps to reproduce the bug:
1. Fill out a new EarthChem record, including funder identifiers
2. Save and observe an error

**Expected behavior**
There should be no error when submitting an earthchem record with funder identifiers.

**Additional information**
[(https://github.com/earthchem/ecl-spec/blob/main/schemas/ECL-JSON-v2.0.0.json#L702-L736)](https://github.com/earthchem/ecl-spec/blob/main/schemas/ECL-JSON-v2.0.0.json#L702-L736)

**Comment by Maurier** [comment]
This appears to have been fixed.
