### ISSUE TITLE
Footer not anchored at the bottom of the page in Safari

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#69]
**Description of the bug**

In Safari, the footer is not anchored at the bottom of the HydroShare submission form and prevents entry of metadata into some of the fields.

Steps to reproduce the bug:
1. Log into Data Submission portal
2. Navigate to any page
3. Scroll down on the page and notice that the footer  is shown in the middle of the page and on top of data entry fields on the data submission forms.

**Expected behavior**

The footer should be anchored at the bottom of the page.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/3485902/181050303-618046ea-af58-4c57-ac99-708fd3e7ba21.png">

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/3485902/181052098-6cd21e23-015d-4917-a582-e4e2aa70e32e.png">

**Comment by cbcunc** [comment]
I can confirm it occurs on my Mac workstation with Safari.
