### ISSUE TITLE
How should we update the DSP version number in the footer?

### ISSUE THREAD

**Issue by cbcunc** [cznethub/dsp#72]
**Describe the feature you'd like and what it will do**
I would like to update the DSP version number in the footer. How do I go about that? (I find 1.0.0 in 138 files in dspfront.)

**Why is this feature important?**
To advertize the currently deployed version.

**Is your feature request related to a problem? Please describe.**
It is not currently advertized entirely truthfully.

**Additional context**
1.0.6 currently deployed. Footer says 1.0.0.

**Comment by sblack-usu** [comment]
[package.json](https://github.com/cznethub/dspfront/blob/c311287adf36a434d8f32081b447bbb87475636b/package.json#L3) has the variable for version number.  We could manually update it each release or we could look into setting it when building or tagging.
