### ISSUE TITLE
Create form for registering existing data from HydroShare, EarthChem, or Zenodo

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#77]
**Describe the feature you'd like and what it will do**

Build a form that enables a user to register a dataset that already exists in the HydroShare, EarthChem, or Zenodo repository with the DSP. I suggest that the existing "Register Dataset" form could be used for this purpose. The user could be presented with a choice about whether they want to register and existing dataset from HydroShare, EarthChem, or Zenodo or register a dataset from a different repository. 
* If they select the first option, they would be prompted to select a repository and provide the URL to the dataset in that repository. The DSP would then connect the dataset to the DSP and fetch the metadata. 
* If they select the second option, they would get the register dataset from External Repository form we have now.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

Multiple CZNet data managers have already created resources in at least the HydroShare repository and need to register them with the DSP.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

I can't currently do this for them. There is a way to do this via a URL, but the user has to do that themselves while logged in to the DSP, and URL construction isn't a great user interface for stuff like this.

**Additional context**

Keep it really simple. The user prompts should be:
1. What repository is the resource in?
2. What is the URL to or identifier for the resource?

**Comment by Maurier** [comment]
@sblack-usu The UI is ready pending a backend endpoint that accepts the repository and resource URL to register the dataset.

POST: `register-dataset/{repository}`
request body: { url: '{resourceUrl}' }

The endpoint method should parse as much data as possible from the resource.

returns the submission entry in our database.

**Comment by sblack-usu** [comment]
@Maurier - sorry I did not respond earlier.  This already exists.  PUT - `/submit/{respository}/{identifier}`

**Comment by Maurier** [comment]
This has been implemented.
