### ISSUE TITLE
Incorrect text at top of submission forms

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#79]
**Description of the bug**

The main title at the top of the submission forms reads "Submit to a" and is incomplete.

Steps to reproduce the bug:
1. Log into the DSP
2. Navigate to the HydroShare, EarthChem, or Zenodo submission forms
3. See the text at the top of the page.

**Expected behavior**

I'm not actually sure what this text is supposed to say, but I'm not sure it's needed.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

HydroShare submission form:
![image](https://user-images.githubusercontent.com/3485902/183714280-d06fd99b-5aff-4d7b-a602-269608f852bf.png)

EarthChem submission form:
![image](https://user-images.githubusercontent.com/3485902/183714366-25b77d3d-f7c9-4ee8-853c-2d10fd193ca1.png)

Zenodo submission form:
![image](https://user-images.githubusercontent.com/3485902/183714441-8c4a4d02-f6de-47f7-a3f4-00dfbf3ad4ab.png)

**Comment by Maurier** [comment]
Related to https://github.com/cznethub/dsp/issues/76

**Comment by Maurier** [comment]
Fixed by #76
