### ISSUE TITLE
Add quick start documentation to the site

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#85]
**Describe the feature you'd like and what it will do**

We have developed some quick start information to a google doc for addition to the site. The Google Doc is here:

https://docs.google.com/document/d/18QbpYPlxXb1BofMl6Dd0kHs_h1l7xYfDKMsLr0UyJSM/edit 

This content should get added to a new page in the site that is then linked to the "Resources" page. On the Resources page, it should appear at the top of the page with a title of "Data Submission Portal Quick Start Guide", a subtitle of "For help getting started with the Data Submission Portal, visit our quick start guide, and then a button with text "Quick Start Guide" that links them to the new page.

**Why is this feature important?**

Users of the DSP may need a little bit of help getting started. This quick start guide provides them with some help content.

**Is your feature request related to a problem? Please describe.**

No problem, just adding documentation.

**Additional context**

N/A

**Comment by Maurier** [comment]
A link to a page with this content has been added at the top of the page at https://dsp.criticalzone.org/resources
