### ISSUE TITLE
HydroShare funding information should be required

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#86]
**Description of the bug**

On the HydroShare submission form, Funding Agency Information is a required section of the metadata. However, when you expand it by clicking on the + button, only the Agency name is required. I believe that is HydroShare's rule, but for the CZNet DSP, I think we want to also require at least the award number and probably also the Award title.

Steps to reproduce the bug:
1. Go to the HydroShare submission form
2. Click on the + in Funding Agency information
3. A new element is created and only the Agency name is shown as required.

**Expected behavior**

Award title and Award number should also be required under Funding agency information

**Additional information**

This is inconsistently handled right now across our submission forms.

**Comment by Maurier** [comment]
Done.
