### ISSUE TITLE
EarthChem Funding Source not required on initial page load

### ISSUE THREAD

**Issue by horsburgh** [cznethub/dsp#87]
**Description of the bug**

When the EarthChem submission form is initially loaded, the "Funding Source" element does not show up as required:

![image](https://user-images.githubusercontent.com/3485902/192388878-d7fd411f-7010-4191-abfd-b5751f88700a.png)

If I click on the + button to add a funding source, then it is indicated as required:

![image](https://user-images.githubusercontent.com/3485902/192388950-e1c0328b-1228-4a34-95a0-d264c1664971.png)

Steps to reproduce the bug:
1. Go to the EarthChem submission form
2. Scroll down to Funding Source
3. It is initially not highlighted in red
4. Click the + button to add a funding source
5. Funding source is now highlighted in red

**Expected behavior**

The "Funding Source" element should be marked as required when the form first loads. 

**Additional information**

N/A

**Comment by Maurier** [comment]
Done. We simply had not specified this field as required in our schema.
