### ISSUE TITLE
Submission form: add drag & drop file operations to file browser interface

### ISSUE THREAD

**Issue by Maurier** [cznethub/dsp#96]
**Describe the feature you'd like and what it will do**
Implement drag & drop UX similar to common OS systems when interacting with files in the file browser interface.

**Why is this feature important?**
To make file browser interface more intuitive.

**Additional context**
Possible dependency: https://www.npmjs.com/package/vue-easy-dnd

**Comment by horsburgh** [comment]
@Maurier - I assume that this issue deals with dragging and dropping files that are already in the UX - e.g., I used the existing drag and drop to put files into the file browser from my computer, but then I might drag a file within the file browser into a folder?

**Comment by Maurier** [comment]
@horsburgh - Correct, both of these examples are now implemented. Closing.
