### ISSUE TITLE
Same keywords of different casing

### ISSUE THREAD

**Issue by Maurier** [cznethub/dsp#98]
**Description of the bug**
Updates to an existing HydroShare resource will fail if the request payload contains a keyword that already exists in the resource in different casing. For example, if the resource already contains a keyword `Cznet`, submitting a request that contains the keyword `CzNet` will throw an error.

A workaround has been put in place to replace occurrences of required keywords with the casing specified in our schema. 

However, this constraint will still cause trouble in instances where different casings of a keyword are desired (i.e: “Urban” is not the same as “urban”).

We need to decide how to handle this and explore if this constraint exists in other repositories and if they can be eliminated.

**Comment by horsburgh** [comment]
@Maurier and @sblack-usu - I'm going to add this one to the v1.3 milestone, but maybe we need to discuss the solution to this one?

**Comment by horsburgh** [comment]
Same keywords with different casing should be regarded as equivalent and should not be attempted to be added to HydroShare.

**Comment by Maurier** [comment]
> Same keywords with different casing should be regarded as equivalent and should not be attempted to be added to HydroShare.

Jeff, should we consider doing the same for EarthChem and Zenodo?

**Comment by horsburgh** [comment]
I think Yes.
